require 'rspec'
require 'capybara/cucumber'
require 'site_prism'
require 'fig_newton'
require 'httparty'
require 'rubygems'
require 'selenium-webdriver'
require 'capybara-screenshot/cucumber'
require 'nokogiri'
require 'screenshot'
require 'csv'
require 'capybara/poltergeist'
require 'unicode_utils/upcase'
require 'faker'
require 'cpf_faker'
require 'rest-client'
require 'net/sftp'
require 'fileutils'
require 'webdrivers'

chrome_options = Selenium::WebDriver::Chrome::Options.new